### ISSUE TITLE
Minimap/Radar

### ISSUE THREAD

**Issue by RizzooTv** [moped-scripts/moped_radar#1]
A config possibility that the minimap is only displayed when you are sitting on the horse / carriage.

**Comment by totsu0jv** [comment]
This already is a thing?  https://github.com/moped-scripts/moped_radar/blob/6a79e1e05ea65251c6c852982955942a9a028a6b/config.lua#L3 by default this is true and it makes it so that when you are on a horse/carriage the radar shows up and when you're on foot its disabled 🤔
